apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-galera
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
        runAsUser: 1000
      #   seLinuxOptions:
      #     level: "s0:c123,c456"
      containers:
        - name: mariadb
          image: mariadb:10.5
          securityContext:
            privileged: true
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "pdns"
          ports:
            - containerPort: 3306
          volumeMounts:
            # - name: mysql-data
            #   mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: mariadb-config
            items:
              - key: "my.cnf"
                path: "my.cnf"
  # volumeClaimTemplates:
  #   - metadata:
  #       name: mysql-data
  #     spec:
  #       storageClassName: manual
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi
