apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-galera
spec:
  serviceName: mariadb
  replicas: 3
  selector:
    matchLabels:
      app: mariadb-galera
  template:
    metadata:
      labels:
        app: mariadb-galera
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
          ports:
            - containerPort: 3306
          # volumeMounts:
          # - name: config-volume
          #   mountPath: /etc/mysql/conf.d
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
          readinessProbe:
            exec:
              command:
                - mysql
                - "-h"
                - "localhost"
                - "-uroot"
                - "-prootpassword" # Use the actual root password set in the environment variable
                - "-e"
                - "SELECT 1"
      volumes:
        - name: config-volume
          configMap:
            name: mariadb-config
            items:
              - key: my.cnf
                path: my.cnf
