---
- name: Deploy VMs for K3s cluster

  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    validate_certs: no
    folder: "{{ folder_name }}"
    resource_pool: "{{ resource_pool }}"
    name: "{{ item.name }}"
    state: present
    template: "{{ vm_template }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_num_cpus }}"
    customization:
      hostname: "{{ item.name }}"
      dns_servers: "{{ dns_servers }}"
      script_text: |
        #!/bin/bash
        echo "{{ vm_user }}:{{ vm_password }}" | chpasswd 
        mkdir -p /home/{{ vm_user }}/.ssh/
        echo {{ pub_ssh_key }} > /home/{{ vm_user }}/.ssh/authorized_keys
        chmod 700 /home/{{ vm_user }}/.ssh
        chmod 600 /home/{{ vm_user }}/.ssh/authorized_keys
        chown -R {{ vm_user }}:{{ vm_user }} /home/{{ vm_user }}/.ssh/
    networks:
      - name: "{{ network_name }}"
        ip: "{{ item.ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        dns_servers: "{{ dns_servers }}"
    wait_for_ip_address: yes
    wait_for_customization: true
  loop: "{{ vms }}"