k3s_cluster:
  children:
    server:
      hosts:
        k3s-master-1:
          ansible_host: <k3s_master_1_ip>
    agent:
      hosts:
        k3s-worker-1:
          ansible_host: <k3s_worker_1_ip>
        k3s-worker-2:
          ansible_host: <k3s_worker_2_ip>
        k3s-worker-3:
          ansible_host: <k3s_worker_3_ip>

  vars: 
      k3s_version: v1.29.2+k3s1
      api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] }}"