apiVersion: v1
kind: Service
metadata:
  name: powerdns
  namespace: "default"
spec:
  type: NodePort
  selector:
    app: powerdns
  ports:
    - name: dns
      port: 53
      targetPort: 5353
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 5353
      protocol: TCP
    - name: web
      port: 8081
      protocol: TCP