- name: Uninstall K3s from all nodes
  hosts: k3s_cluster
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Run K3s uninstallation script [server]
      when: inventory_hostname in groups['server']
      ansible.builtin.command:
        cmd: k3s-uninstall.sh
      ignore_errors: true
      
    - name: Run K3s uninstallation script [agent]
      when: inventory_hostname in groups['agent']
      ansible.builtin.command:
        cmd: k3s-agent-uninstall.sh
      ignore_errors: true

    - name: Remove K3s installation script
      ansible.builtin.file:
        path: /usr/local/bin/k3s-install.sh
        state: absent

    - name: Check for common K3s directories and files
      ansible.builtin.stat:
        path: "{{ item }}"
      register: result
      loop:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
        - /var/lib/kubelet
        - /etc/systemd/system/k3s.service
        - /usr/local/bin/k3s
        - /usr/local/bin/kubectl
        - /usr/local/bin/crictl

    - name: Display check results
      ansible.builtin.debug:
        msg: "Path '{{ item.item }}' exists: {{ item.stat.exists }}"
      loop: "{{ result.results }}"