---
- name: Prepare infrastructure
  hosts: k3s_cluster
  become: true
  become_method: ansible.builtin.sudo
  roles: 
    - prereq

- name: Install K3s on server nodes
  hosts: server
  become: true
  become_method: ansible.builtin.sudo
  roles: 
    - k3s_server

- name: Install K3s on agent nodes
  hosts: agent
  become: true
  become_method: ansible.builtin.sudo
  roles: 
    - k3s_agent