apiVersion: v1
kind: Service
metadata:
  name: powerdns
  labels:
    app: powerdns
  namespace: "default"
spec:
  selector:
    app: powerdns
  ports:
  - name: dns-udp
    port: 5353
    targetPort: 5353
    protocol: UDP
  - name: dns-tcp
    port: 5353
    targetPort: 5353
    protocol: TCP
  - name: api
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: LoadBalancer